name: Build

on:
  push:
    branches-ignore:
      - 'feature/**'
    tags-ignore:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: $EntityAccess2023
          MSSQL_PID: Express
        ports:
          - 1433:1433

      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: abcd123
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3.2.0
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/        
      - run: npm install
      - run: npm install -D typescript
      - run: tsc
      - run: npm run test
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432